repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--check"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: ["pydantic"]
        files: ^src/services/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-r", "src/services", "-lll"]

  - repo: https://github.com/pytest-dev/pytest
    rev: 8.3.2
    hooks:
      - id: pytest
        name: pytest (fast subset)
        entry: pytest -q -m "not slow and not gpu and not e2e"
        language: system
        types: [python]
        pass_filenames: false
